# Generated by Django 5.1.1 on 2024-09-30 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(max_length=10)),
                ('icao', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=80)),
                ('country_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AirplaneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('seating_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=80)),
                ('timezone', models.CharField(max_length=20)),
                ('full_timezone', models.CharField(max_length=80)),
                ('utc_offset', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=80)),
                ('utc_offset', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=10)),
                ('airplain_type_name', models.CharField(max_length=80)),
                ('airline_name', models.CharField(max_length=80)),
                ('airline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='airport.airline')),
                ('airplain_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='airport.airplanetype')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('country_code', models.CharField(max_length=80)),
                ('timezone_full', models.CharField(max_length=80)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='airport.country')),
                ('timezone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='airport.timezone')),
            ],
        ),
        migrations.AddField(
            model_name='airline',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='airport.country'),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airport.airline')),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airport.airplane')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrival', to='airport.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departure', to='airport.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.CharField(max_length=20)),
                ('seat_number', models.CharField(max_length=10)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airport.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('residence', models.CharField(max_length=80)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airport.ticket')),
            ],
        ),
    ]
