# Generated by Django 5.1.1 on 2024-09-30 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplane',
            old_name='airplain_type_name',
            new_name='airplane_type_name',
        ),
    ]
