# Generated by Django 5.1.1 on 2024-09-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_rename_airplain_type_name_airplane_airplane_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='full_timezone',
        ),
        migrations.RemoveField(
            model_name='country',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='country',
            name='utc_offset',
        ),
    ]
