# Generated by Django 5.1.1 on 2024-09-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_remove_country_full_timezone_remove_country_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timezone',
            name='fullname',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
    ]
