# Generated by Django 5.1.1 on 2024-09-30 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_timezone_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplane',
            old_name='airplain_type',
            new_name='airplane_type',
        ),
    ]
