# Generated by Django 5.1.1 on 2024-10-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0005_rename_airplain_type_airplane_airplane_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplanetype',
            old_name='model',
            new_name='name',
        ),
    ]
