# Generated by Django 5.1.1 on 2024-10-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0006_rename_model_airplanetype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='airline_name',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='airplane_type_name',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='timezone_full',
        ),
    ]
